import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import CreateEventDrawer from "@/components/create-event";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="min-h-screen bg-gradient-to-b from-blue-100 to white">
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </main>

          {/* Footer  */}
          <footer className="bg-blue-100 md:py-5 hidden md:block">
            <div className="container mx-auto px-4 text-center text-gray-600">
              Made with 🖤 by Sai Jami
            </div>
          </footer>
          <Suspense fallback={<>Loading...</>}>
          <CreateEventDrawer />
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
